---
- name: Uninstall tree
  hosts: all
  become: yes  # This enables privilege escalation to execute commands with root permissions

  tasks:
    - name: Remove tree package
      apt:
        name: tree
        state: absent
...        
