
---
- name: Ensure web server is running
  hosts: all
  vars:
    http_port: 80
  tasks:
    - name: Ensure apache is running
      service:
        name: apache2
        state: started
  vars_files:
    - vars/common.yml

...