---
- name: playbook-1
  hosts: all
  tasks:
    - name: writing my first script 
      debug:
        msg: "{my first playbook is operational now}"
    - name: this is next content
      debug:
        msg: "{this is script two}"
...        
