---
- name: Ensure web server is running
  hosts: all
  vars:
     URL: "working on varibles "
  tasks:   
    - name: "working on varible first script"
      debug: 
        msg: "{{URL}}"
...       