---
- name: Ensure web server is running
  hosts: all
  vars:
     URL: "working on global varibles "
  tasks:   
    - name: "working on varible first script"
      debug: 
        msg: "{{URL}}"  
    - name: "working on varible first script"
      debug: 
        msg: "{{URL}}"
    - name: "Working on local varibles" 
      vars:
        string: "this is local varibles"
      debug:
        msg: "{{string}}"     
...       